### ISSUE TITLE
建议修改如下：

### ISSUE THREAD

**Issue by Leadrive** [cloudwebrtc/flutter-webrtc-server#10]
1、nginx.conf中，增加/wss二级目录，配置参考如下：
<prev>

upstream webrtcServer {
    server 0.0.0.0:8086;
}
upstream webrtcWSS {
    server 0.0.0.0:4443;
}
</prev>
<prev>

server {
    listen 443 ssl;
    server_name webrtc.touroad.cn;
    index index.html index.htm index.php;
    ssl on;
    ssl_certificate /home/ssl/x.xxx.cn.pem;
    ssl_certificate_key /home/ssl/x.xxx.cn.key;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    gzip_min_length 1k;
    gzip_comp_level 2;
    gzip_types text/plain text/css application/xml image/jpeg image/gif image/png image/jpg text/javascript application/javascript;

    location / {
        proxy_pass https://webrtcServer;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location /wss {
        proxy_pass https://webrtcWSS;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
</prev>

2、flutter-webrtc-server/src/App.js
第79行，修改为
<prev>

    var url = 'wss://' + window.location.hostname + '/wss';
</prev>

3、flutter-webrtc-demo/lib/src/call_sample/call_sample.dart
第53行，修改为
<prev>

      _signaling = new Signaling('wss://' + serverIP + '/wss', _displayName)
</perv>

4、flutter-webrtc-demo/lib/src/call_sample/data_channel_sample.dart
第48行，修改为
<prev>

      _signaling = new Signaling('wss://' + serverIP + '/wss', _displayName)
</prev>

这样，客户端就可以不用开4442，4443端口。
通过 wss://x.xxx.cn/ww 就可以访问 wss
供参考。

另外，请教下，有windows版本的客户端demo吗？

**Comment by cloudwebrtc** [comment]
项目没有使用nginx， 只是简单的node + express.

**Comment by cloudwebrtc** [comment]
```另外，请教下，有windows版本的客户端demo吗？```

win/macos/linux 版目前依赖 [flutter-desktop-embedding](github.com/google/flutter-desktop-embedding) 项目，目前还需要等待 https://github.com/google/flutter-desktop-embedding/issues/107 解决才能往前推进.
