### ISSUE TITLE
Just seeing navbar with Firefox Quantum 65.0.1

### ISSUE THREAD

**Issue by pitazzo** [cloudwebrtc/flutter-webrtc-server#11]
I've managed to build and deploy the `flutter-webrtc-server` package. I've tested it with Google Chrome in two mobile devices and it worked just as expected. 
However, when trying to access to the HTML5 demo via Firefox, I can only see the blue navbar. I'm aware of #3 and I have both opened two tabs and tried https://localhost:8086, but I can't get it working.
I'm facing the same issue when connecting to https://demo.cloudwebrtc.com:8086/, therefore I think it has to be something browser-related.
- Firefox Quantum 65.0.1

**Comment by cloudwebrtc** [comment]
Please provide some console logs from firefox.
