### ISSUE TITLE
Can't see the users connected to localhost

### ISSUE THREAD

**Issue by eduardmo** [cloudwebrtc/flutter-webrtc-server#12]
Hello,
I'm trying to set up the server and I ran into some problems.
I successfully started the project with "npm start" but when I connect to https://0.0.0.0:8086 nothing happens. I can see the blue bar but that's it. I tried connecting in the same time with Mozilla, Chrome and an Android phone and none update. 
After this I tried deploying it on heroku but it fails. You can see it [here](http://prntscr.com/mzonpo). 
I have a turn server because now I'm rewrtiting my application and I had another signaling server before but I'm not sure how to make this work. Please help me! Thank you! ^_^

**Comment by rostopira** [comment]
4 zeros IP?
You've done something terribly wrong, and I don't even know, at which step

**Comment by eduardmo** [comment]
I can access https://localhost:8086 as well and the same happens.

**Comment by rostopira** [comment]
Well, then
Blue bar at the top indicates, that you have connected to yourself
Now you need to connect other device or devices
But that won't work with localhost obviously
You need to enter you local network IP on other device
It must start with 192.168.X.X

**Comment by eduardmo** [comment]
Alright. That makes sense. If I open 2 Chrome tabs and connect them to 192.168.X.X:8086 I can see both tabs in the list, even start a call (So my Turn server works). When I do that from Mozilla, it doesn't appear in the list and the console shows "Firefox can’t establish a connection to the server at wss://192.168.X.X:4443/.". This might be the same issue as the other opened issue.
I can't connect to the server through the app as well but I'm thinking this might be because the connection is not secured (I think).
Anyway, I don't really care about the browser (I just wanted to see if I set up the Turn server correct) and I would like to upload the signaling server on Heroku. Do you know why that error pops up? I added a screenshot of it in the issue. Thank you very much for your time!

**Comment by linhaosunny** [comment]
I also get 4 zero IP, what's wrong?

**Comment by devibrahimkarahan** [comment]
You need to enter computers ip address in android server address for see android users on web.

**Comment by miroslave-ivan** [comment]
I entered my computer ip address in android server address for see android users on web.
But results is same. I can't see nothing, just my computer webapp.
please explain to me other way for the issue. thanks

**Comment by MuhammadAliKhan1** [comment]
Same issue

**Comment by kenz68** [comment]
> Hello,
> I'm trying to set up the server and I ran into some problems.
> I successfully started the project with "npm start" but when I connect to https://0.0.0.0:8086 nothing happens. I can see the blue bar but that's it. I tried connecting in the same time with Mozilla, Chrome and an Android phone and none update.
> After this I tried deploying it on heroku but it fails. You can see it [here](http://prntscr.com/mzonpo).
> I have a turn server because now I'm rewrtiting my application and I had another signaling server before but I'm not sure how to make this work. Please help me! Thank you! ^_^

I have then same error when I tried deploying it on heroku, any advices, please help me. Thanks
