### ISSUE TITLE
Not managed to test using connected iPhone with ngrok

### ISSUE THREAD

**Issue by kittlsk** [cloudwebrtc/flutter-webrtc-server#14]
Hi,

I tested using iPhone simulator and I entered localhost as server address for P2P Call Sample.  I managed to get connected to the server and can establish video call (no visual from simulator though but visual from webapp works). So I tried using connected iPhone to test the visual, and entered the ngrok host name to tunnel localhost:8086, I can't get connected to the server.  Anyone has solution for this?

**Comment by rostopira** [comment]
You have to enter ip of your server, not localhost
Let's say you are running it's on wifi network on macbook, and your macbook has IP address 192.168.0.12 on your wifi network. So you must enter 192.168.0.12:8086
localhost is just 127.0.0.1 which loops to your iphone, which obviously doesn't have server running on it

**Comment by rostopira** [comment]
I missed "emulator" word

**Comment by kittlsk** [comment]
thanks to @rostopira this issue is solved by using 198 server ip address.

**Comment by kamrancr7** [comment]
@kittlsk how you solved that issue?
