### ISSUE TITLE
Some cases are not working.

### ISSUE THREAD

**Issue by phamnhuvu-dev** [cloudwebrtc/flutter-webrtc-server#15]
I have tested the flowing cases:

- Web browser (Chrome):
. Linux to Android: OK
. Linux to MacOS: Fail
. Android to Linux: Fail
. Android to MacOS: Fail
. iOS: Fail - just show top bar
. MacOS to all cases: 
> Uncaught (in promise) DOMException
Promise.then (async)
Signaling._this.invite @ Signaling.js:152
App._this.handleInvitePeer @ App.js:119
onClick @ App.js:197
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:270
executeDispatch @ react-dom.development.js:561
executeDispatchesInOrder @ react-dom.development.js:583
executeDispatchesAndRelease @ react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:688
forEachAccumulated @ react-dom.development.js:662
runEventsInBatch @ react-dom.development.js:816
runExtractedEventsInBatch @ react-dom.development.js:824
handleTopLevel @ react-dom.development.js:4826
batchedUpdates$1 @ react-dom.development.js:20439
batchedUpdates @ react-dom.development.js:2151
dispatchEvent @ react-dom.development.js:4905
(anonymous) @ react-dom.development.js:20490
unstable_runWithPriority @ scheduler.development.js:255
interactiveUpdates$1 @ react-dom.development.js:20489
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882

- Mobile app:
. Android to iOS: OK
. iOS to Android: OK

- Mobile with Web Browser:
. Mobile to web browser (Desktop): Fail
. Web browser (Desktop) - Mobile: Ok
. Mobile browser to Mobile: Ok
. Mobile to mobile browser: Ok

**Comment by cloudwebrtc** [comment]
May not get getUseMedia permission or self-signed certificate issue.

**Comment by ShilpaVania** [comment]
@phamnhuvu-dev 
I have implemented streaming feature in mobile app using flutter 
there are some case when rendering is not working and the case is when i live from ios device and join video from android device it is working proper but after left once joined again and repeat till 3 times only it's works
after 4th time stream is not rendering and also i am getting track id with audio and video but not rendering 
does you have idea about it?
