### ISSUE TITLE
Why does this not work over the internet?

### ISSUE THREAD

**Issue by cdharris** [cloudwebrtc/flutter-webrtc-server#16]
Hi! Thanks for what looks like the start of a great library.

Do you know why it doesn't work over the internet? Even with appropriate STUN/TURN servers?

(I notice you say it only works on local LAN)

**Comment by cloudwebrtc** [comment]
You need to deploy the turn server, then you can work on the internet.

**Comment by cdharris** [comment]
hmm I tried with my own turn server and that still didn't work. Also tried your example at demo.cloudwebrtc.com:8086 . That doesn't work either with two mobile chrome browsers over internet. (The clients connect, and both local video is streamed locally, but the remote video is just a grey screen and never starts streaming. Firefox says ICE failed)

**Comment by cloudwebrtc** [comment]
You can check if the server is normal by the following example, and check the browser log to see if any realy candidate have been collected.

https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by cdharris** [comment]
Thanks, finally got the turn configuration setup working. Coturn was a bit difficult to work out :)

**Comment by PrakharPatidar** [comment]
Hi @cdharris . I am also facing the same issue. I am able to connect on local devices with the same LAN network but not over the internet. I have also configured TURN serer as below:
== > 
```
config: {
                "iceServers":[{"urls":["turn:numb.viagenie.ca?transport=tcp"],"username":"webrtc@live.com","credential":"muazkh"}],
}
```

Could you please share how did you solve this issue?

**Comment by abheet-98** [comment]
@PrakharPatidar Hey hope you are doing well !
I just wanted to know if you got the accurate P2P call between two mobile devices using the server running on a chrome browser where mobile devices and the laptop are connected to the same Wifi connection?
Actually my server starts running on the browser and when I type the ip address in the mobile I can see only the blank screen and the mobile device don't get added to the list of devices on the server.

![image](https://user-images.githubusercontent.com/42749352/83330595-b18bea00-a2ad-11ea-8f1c-06d4c2421487.png)

![image](https://user-images.githubusercontent.com/42749352/83330600-bc467f00-a2ad-11ea-91cc-68cfaff6fad2.png)

If you could just help me to have a P2P call between 2 mobile devices using this server.

Thanks in advance!
