### ISSUE TITLE
P2P Call Sample

### ISSUE THREAD

**Issue by sabriismail4** [cloudwebrtc/flutter-webrtc-server#19]
Hello @cloudwebrtc ,
I am trying to establish a video call between the mobile application using the given demo (https://github.com/cloudwebrtc/flutter-webrtc-demo) and a PC web browser using server demo (https://github.com/cloudwebrtc/flutter-webrtc-server). There isn't any issue when I try to establish the connection from the emulator's browser, but as I said my goal is to reach out from the flutter mobile app demo.
I read the previous issues, in one of which there was mentioned the iceServers[], but still couldn't understand how and what do I exactly need to change. I tried to replace here in {"url": "stun:stun.l.google.com:19302"} the (stun:stun.l.google.com:19302) part with the localhost ip address (192.x.x.x) + the port (8086). Maybe I've done it wrong I don't know and that's why I am raising this topic here ? 
Thanks in advance!

**Comment by cloudwebrtc** [comment]
stun server is about WebRTC media transmission, and what you said is 192.168.X.X: 8086 is the web server for html app

**Comment by miroslave-ivan** [comment]
hi, cloudwebrtc
please explain me more correctly. 
I don't know well about it, too.
thanks

**Comment by sabriismail4** [comment]
> stun server is about WebRTC media transmission, and what you said is 192.168.X.X: 8086 is the web server for html app

Well, could you kindly describe in more details what it needs to be done, because I am getting confused, since we don't have the knowledge you do. Please update the README.md documentation in more details, since the implementation talks nothing to me, also try to answer earlier than 5 months, because things are being left behind and forgotten :) 
Best regards!

**Comment by johnnydevvcodes** [comment]
Any solution on this yet?

**Comment by jason-shen** [comment]
> > stun server is about WebRTC media transmission, and what you said is 192.168.X.X: 8086 is the web server for html app
> 
> Well, could you kindly describe in more details what it needs to be done, because I am getting confused, since we don't have the knowledge you do. Please update the README.md documentation in more details, since the implementation talks nothing to me, also try to answer earlier than 5 months, because things are being left behind and forgotten :)
> Best regards!

i think you should learn webrtc concepts before jump into something like this.

put it simple stun is just a server that give what your external ip and then it gets send with the peer connection
