### ISSUE TITLE
Failed to build on ubuntu 18.08 with latest node/NPM installed

### ISSUE THREAD

**Issue by macbroadcast** [cloudwebrtc/flutter-webrtc-server#2]
`~/webrtc$` git clone https://github.com/cloudwebrtc/flutter-webrtc-server.git
Cloning into 'flutter-webrtc-server'...
remote: Counting objects: 194, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 194 (delta 1), reused 3 (delta 1), pack-reused 189
Receiving objects: 100% (194/194), 2.61 MiB | 4.72 MiB/s, done.
Resolving deltas: 100% (95/95), done.
stream@bayradio:~/webrtc$ ls
flutter-webrtc-server
stream@bayradio:~/webrtc$ cd flutter-webrtc-server
stream@bayradio:~/webrtc/flutter-webrtc-server$ ls
LICENSE    certs         screenshots  src
README.md  package.json  server       webpack.config.js
stream@bayradio:~/webrtc/flutter-webrtc-server$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
extract:mamacro → gunzTar ▐ ╢██████████████████████████████████░░░░░░░░░░░░░░░╟
Killed
stream@bayradio:~/webrtc/flutter-webrtc-server$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
extract → gentlyRm        ▀ ╢██████████████████████████████████░░░░░░░░░░░░░░░╟

**Comment by kang-airtc** [comment]
@macbroadcast hi guy.   what's your npm and node version?
