### ISSUE TITLE
0.0.0.0:8086 not loading, saying this site cant be reached

### ISSUE THREAD

**Issue by neenabastin123** [cloudwebrtc/flutter-webrtc-server#21]
I am new to node.js. Since I need webrtc in flutter, I need both server and flutter webrtc. So when I install and start npm, though the page is loading 0.0.0.0:8086, this site cant be reached error showing.

**Comment by neenabastin123** [comment]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html

**Comment by neenabastin123** [comment]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./src/index.js] 166 bytes {main} [built]
    + 331 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = ./index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 370 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
i ｢wdm｣: Compiled successfully.

**Comment by devibrahimkarahan** [comment]
Try 127.0.0.1:8086 or localhost:8086

**Comment by neenabastin123** [comment]
Can you please help me? where to change the ip address? I am a flutter developer and dont know much about node js. I do not know what I am doing is right or wrong. I tried to change the express server ip address, showing error. Can you help me where to change the ipAddress to make this work?

**Comment by GooDong** [comment]
> Can you please help me? where to change the ip address? I am a flutter developer and dont know much about node js. I do not know what I am doing is right or wrong. I tried to change the express server ip address, showing error. Can you help me where to change the ipAddress to make this work?

open file name  "package.json" ,  and you need find  words like "--host".

**Comment by neenabastin123** [comment]
Thank you, it worked.

**Comment by miroslave-ivan** [comment]
Try 127.0.0.1:8086 or localhost:8086 or your local Ip:8086
