### ISSUE TITLE
Technology used for this server project

### ISSUE THREAD

**Issue by neenabastin123** [cloudwebrtc/flutter-webrtc-server#23]
Many thanks for which you created a project for peer to peer call. I am an android/flutter developer and I would like to use this flutter project inside my project but I dont know how to use this server project so that I can check the flutter demo, Can you tell me which languge the server project is written? Which IDE  I have to use to open this server project? Any help will be much appreciated

**Comment by cloudwebrtc** [comment]
This is a nodejs project, you can use vscode to develop it and run the project with
 `npm i && npm start`
