### ISSUE TITLE
Only Navbar visible

### ISSUE THREAD

**Issue by myhendry** [cloudwebrtc/flutter-webrtc-server#3]
Hi. I managed to compile using npm start. However, when i visited the page https://localhost:8086/, i only see a blue navbar and nothing else.  On the left side of the url, it just indicates 'Not Secure'. What should I do to get it working? btw, i using a chrome browser on macos. thanks

**Comment by cloudwebrtc** [comment]
You can try open https://localhost:8086/ on multiple tabs on Chrome. Normally you can see other Peers logged in to the server and click the video image button to connect to other peers.

**Comment by gannonbarnett** [comment]
This issue/solution should be in the readMe, would be very useful. Not immediately clear that you need two tabs/users open to see any connections.
