### ISSUE TITLE
TLS handshake error from [::1]:57330: remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by kushankurxd** [cloudwebrtc/flutter-webrtc-server#32]
I tried running server on localhost its cool. But when trying to use flutter web to connect to localhost server it throws this exception.

![snapshot](https://user-images.githubusercontent.com/37204706/80155198-dc17c280-85de-11ea-9dec-8a0d9959328d.PNG)

I think there is problem with the SSL public  certificate validation as I looked into it its validation is upto April 2019.

Thanks in advance :)

**Comment by chhota89** [comment]
@kushankurxd How to resolve this issue?

**Comment by abheet-98** [comment]
@kushankurxd How did you resolve this issue?
It'll be very kind of you if you explain us the solution.
Thanks in advance !

**Comment by abheet-98** [comment]
@kushankurxd 
Is your issue resolved?

**Comment by abheet-98** [comment]
@chhota89 Is your issue resolved?

**Comment by bugrakufeci** [comment]
I couldn't solve the issue but I noticed that I get handshake error only on browser, it works fine on mobile devices/emulators.

Also I have noticed that there is no issue on old version. You can reach it on branches > old. It works completely fine, might be a temporary solution. @abheet-98

**Comment by abheet-98** [comment]
Thanks for a response @tavuskusu  !
Actually I'm not able to have a p2p call and couldn't get proper instructions by reading the README.md So if you could help me out to have a p2p call between 2 phones on the same network using this webrtc server.
If you could tell me in steps how to have a quick test of this demo app and the webRTCserver .
Thanks !

**Comment by bugrakufeci** [comment]
Of course. First of all, you run the server from console.(It's server-windows-xxx.exe on master and npm start on old version). 
You should check your machine's ip by running "ipconfig" on another console, you should see something like "192.168.xx.xx" (which is IPv4 adress). Thats your server ip which you will enter on app.

While server is running, you can run the demo app on devices. Then you go to P2P call sample, enter the "192.168.xx.xx" on the dialog, then you connect. You will see yourself and other connected devices as list. You can screenshare or do a video call via those buttons. Let me know if you come across any issues. Good luck!

**Comment by abheet-98** [comment]
@tavuskusu Thank you !
Now my server started running using the old branch .
![Capturedemoapp](https://user-images.githubusercontent.com/42749352/83247051-9f804d80-a1c0-11ea-939b-1c8a3c865438.PNG)

But when I type the server ip on the demo app on 2 mobile devices the P2P call sample screen shows blank white screen with navbar "P2P call sample"
![image](https://user-images.githubusercontent.com/42749352/83247229-dbb3ae00-a1c0-11ea-8c79-cb45ba76154c.png)
Thank you !

**Comment by abheet-98** [comment]
@tavuskusu  Is there any solution for this ?
I'm stuck here.

> @tavuskusu Thank you !
> Now my server started running using the old branch .
> ![Capturedemoapp](https://user-images.githubusercontent.com/42749352/83247051-9f804d80-a1c0-11ea-939b-1c8a3c865438.PNG)
> 
> But when I type the server ip on the demo app on 2 mobile devices the P2P call sample screen shows blank white screen with navbar "P2P call sample"
> ![image](https://user-images.githubusercontent.com/42749352/83247229-dbb3ae00-a1c0-11ea-8c79-cb45ba76154c.png)
> Thank you !
