### ISSUE TITLE
about server setup?

### ISSUE THREAD

**Issue by bilalbaz1** [cloudwebrtc/flutter-webrtc-server#35]
How can I edit the ... /config/config.ini file and put it on the server?
**can you also explain how to put this project on the server and run it?**

**Comment by tahaafg20** [comment]
Having the same issue.
Any solutions?

**Comment by efraespada** [comment]
Same problem/doubt here

**Comment by efraespada** [comment]
No server needed. 😃

Following the [Mozilla signaling documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling) and the [flutter demo repository](https://github.com/flutter-webrtc/flutter-webrtc-demo), you can make the signaling flow with a simple Firebase Database (Cloud Firestore or Realtime Database).

Replacing the [`_send()`](https://github.com/flutter-webrtc/flutter-webrtc-demo/blob/8ada749baeeeb828df5eec8b48985e9f43f8cfaf/lib/src/call_sample/signaling.dart#L348) method with your Firebase implementation:

```dart
Future setCallData(String groupId, String userId, String type, Map<String, dynamic> data) async {
  try {
    final DocumentReference ref = FirebaseFirestore.instance
        .collection(GroupsRepository.collection)
        .doc(groupId);

    await ref.update({
      "members.$userId.callData.type": type,
      "members.$userId.callData.data": data,
    });
  } catch (e) {
    print(e);
  }
}
```

When observing the changes in the group, check all the `members/$any_userId/callData` and handle anything related with the current user (when `$userId == members/$any_userId/callData/data/to`) with the [`onMessage()`](https://github.com/flutter-webrtc/flutter-webrtc-demo/blob/master/lib/src/call_sample/signaling.dart#L137) method.

```dart
{
 'to': id,
 'from': _selfId,
 'candidate': {
          ....
  },
  'session_id': this._sessionId,
}
```


[This guy](https://www.youtube.com/watch?v=-d45WHNU9J4) shows this concept in a React app.
