### ISSUE TITLE
Configs path error

### ISSUE THREAD

**Issue by cardoza868** [cloudwebrtc/flutter-webrtc-server#36]
Getting the following Error:

[90m2020-05-26T12:15:44-04:00[0m [1m[31mERR[0m[0m Fail to read file: open configs/config.ini: The system cannot find the path specified.

**Comment by SpenceAcc** [comment]
I have same problem，but I solve .
for windows  cmd
step 1
open cmd
step 2
cd flutter-webrtc-server
step 3
 .\bin\server-windows-amd64.exe

**Comment by jhswedeveloper** [comment]
I guess it depends on how the setup looks like.

I did a setup with systemd 

The important part is setting the WorkingDirectory 
```
[Unit]
Description=goweb

[Service]
Type=simple
WorkingDirectory=/home/flutter-webrtc-server
ExecStart=/home/flutter-webrtc-server/main

[Install]
WantedBy=multi-user.target
```
