### ISSUE TITLE
Doc should say to open port 4442

### ISSUE THREAD

**Issue by function1983** [cloudwebrtc/flutter-webrtc-server#4]
Thank you for the project.

Though port 4442 is in the code, either your readme file here or on the flutter client should clearly say to open port 4442 in order for flutter clients to connect. It helps people to run a quick test.

Also, is it just me or firefox on Ubuntu cannot connect to the server, only chrome does?

Thanks.

**Comment by cloudwebrtc** [comment]
Apologies for the late reply. 
Firefox needs a  public domain name and SSL certificate, you can try connect to  port 4442 using WS for test.
