### ISSUE TITLE
Getting rid of built-in turn server

### ISSUE THREAD

**Issue by oguzhancelikarslan** [cloudwebrtc/flutter-webrtc-server#49]
I only want to use signaling part of the package. How can I get rid of built-in ones? Can you suggest me some documentation to create my own signaling server with different language?

**Comment by jason-shen** [comment]
You can check the app socket events and easily write the signaling with nodejs if u don't want to use go

**Comment by oguzhancelikarslan** [comment]
> You can check the app socket events and easily write the signaling with nodejs if u don't want to use go

Solved my problem!
