### ISSUE TITLE
build and run scuuess,but I can see other client list when I tap top_left button

### ISSUE THREAD

**Issue by linguitang** [cloudwebrtc/flutter-webrtc-server#5]

**Comment by rostopira** [comment]
So, what's the problem? 0_o

**Comment by linguitang** [comment]
how can I see other client list?

**Comment by rostopira** [comment]
What do you mean? You can see only those clients, who are connected to your local server

**Comment by cloudwebrtc** [comment]
By default, when there is only one client, it will not display its own label, and at least two client connections are required to initiate a call.
I have updated it, please update the latest version and have added display of your own label. 82a83e6407ccc921da64e3cf9b8c475317a39d9c
