### ISSUE TITLE
What next ? 

### ISSUE THREAD

**Issue by krvcz** [cloudwebrtc/flutter-webrtc-server#51]
Sorry, i am beginner. I got server on 0.0.0.0:8086, what i should do if i want start call video in local network ?

**Comment by cloudwebrtc** [comment]
You can open multiple pages at https://0.0.0.0:8086, enter p2p call sample to see the list of members, click to call.

**Comment by krvcz** [comment]
Can i do it on other devices? For example in local network ? If yes , how it setup ?
