### ISSUE TITLE
Can mobile devices act as signaling server?

### ISSUE THREAD

**Issue by fikrirazzaq** [cloudwebrtc/flutter-webrtc-server#52]
Hi, want to ask about the possibilities of Mobile Devices (Android, iOS, Tablet) act as signaling server. Any chance of that?

Thanks.

**Comment by esenmx** [comment]
I'm not expert but as far as I know, signaling server should be NAT agnostic, since this is impossible for mobile devices, it's also impossible for using it as signaling server.
