### ISSUE TITLE
failed to connect

### ISSUE THREAD

**Issue by nitishpatel** [cloudwebrtc/flutter-webrtc-server#55]
I tried running the go server and the webrtc-demo repo on the local machine and added the local server URL 
but it won't connect

connect to https://0.0.0.0:8086:8086/ws
Closed by server [500 => SyntaxError: Failed to construct 'WebSocket': The URL 'wss://0.0.0.0:8086:8086/ws' is
invalid.]!
![image](https://user-images.githubusercontent.com/39486276/110108052-b39d4f00-7dd1-11eb-8fbe-87dfa8117f59.png)

**Comment by cloudwebrtc** [comment]
please try https://0.0.0.0:8086:8086/ws change to https://0.0.0.0:8086/ws.
