### ISSUE TITLE
video don't display in one side. 

### ISSUE THREAD

**Issue by soring323** [cloudwebrtc/flutter-webrtc-server#58]
video is playing perfectly only one side. 
i guess it relates with SDK update. 
is there someone that fixed this already?

**Comment by updev0612** [comment]
Hi. I've got same issue after update SDK. 
any luck?

**Comment by Shanki070** [comment]
The same issue I am facing, any code to fix it.

**Comment by Shanki070** [comment]
check this link: 
https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/118#issuecomment-801804745
