### ISSUE TITLE
Make Certs work fully in local browser for testing

### ISSUE THREAD

**Issue by ghost** [cloudwebrtc/flutter-webrtc-server#6]
This is really useful so your can make sure your DEV environment exactly matches your PROD environment with regards to Certs.

https://blog.filippo.io/mkcert-valid-https-certificates-for-localhost/
https://github.com/FiloSottile/mkcert

**Comment by cloudwebrtc** [comment]
Please refer to https://github.com/cloudwebrtc/flutter-webrtc-demo/issues/8

**Comment by cloudwebrtc** [comment]
Not the problem of the project itself
