### ISSUE TITLE
signalserver in combination with coturn

### ISSUE THREAD

**Issue by fre391** [cloudwebrtc/flutter-webrtc-server#64]
First I have installed the flutter-webrtc-server (without coturn) and it was running fine in most scenarios with flutter-webrtc on mobile. I followed the instruction at: https://larrylisky.com/2020/05/22/implementing-flutter-webrtc-client-and-server/

As a next step I installed coturn (on the same machine). I also tested my Coturn instance successfully with Trickle ICE and it seems to run fine. I followed the instructions at https://meetrix.io/blog/webrtc/coturn/installation.html

But I can no more start the flutter-webrtc-server now.  It says it failed to create TURN server listener:
PNC Failed to create TURN server listener: listen udp4 0.0.0.0:3478: bind: address already in use
panic: Failed to create TURN server listener: listen udp4 0.0.0.0:3478: bind: address already in use

I can confirm that I use the following configurations:
For flutter-webrtc-server in config.ini:
...
bind=0.0.0.0
port=8086
...

For Coturn in turnserver.conf:
...
listening-ip=0.0.0.0
listening-port=3478
...

It would be great if anybody could help me out and point me in the right direction. What do I miss here?

Thank you so much for your project..I enjoy it very much exploring webrtc...

**Comment by supermuesli** [comment]
**your udp port 3478 is already in use since coturn uses it**. i'm assuming you set your ```flutter-webrtc-server``` turn port to 3478 as well, did you not? in that case, choosing a different turn port (in ```config.ini```) should solve your issue. note that ```flutter-webrtc-server``` starts its own turn server (```pion/turn```) on the port that you provide in ```config.ini```.

**Comment by fre391** [comment]
Yeay, thanks for letting me know. It works like a charm. Thank you so much again!
