### ISSUE TITLE
Invalid Host header 的解决方法

### ISSUE THREAD

**Issue by Leadrive** [cloudwebrtc/flutter-webrtc-server#7]
运行后，用 https://ip:8086访问是没问题。
如果用域名指向，则会报 Invalid Host header

参考 https://blog.csdn.net/baidu_33614459/article/details/80055021

在webpack.config.js中加入
devServer: {
      disableHostCheck: true,
    }

**Comment by cloudwebrtc** [comment]
谢谢，已经更新 https://github.com/cloudwebrtc/flutter-webrtc-server/commit/39c7522df4ba8d4e4358dd95de0d369094f18e2a
